trigger:
  - main  # Runs the pipeline when changes are pushed to 'main' branch

pool:
  name: Default  # Make sure this matches the agent pool where "my-local-agent" is registered
  demands:
    - Agent.Name -equals my-local-agent2  # Ensures it runs on your agent

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Building HTML site..."
        mkdir -p $(Build.ArtifactStagingDirectory)/site
        cp -r * $(Build.ArtifactStagingDirectory)/site
      displayName: "Prepare HTML Artifacts"

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/site'
        artifactName: 'html-site'

- stage: Deploy
  jobs:
  - job: DeployToLocalServer
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'html-site'
        downloadPath: '$(Build.ArtifactStagingDirectory)'

    - script: |
        echo "Deploying files to /var/www/html"
        sudo rm -rf /var/www/html*
        sudo cp -r $(Build.ArtifactStagingDirectory)/html-site/* /var/www/html
        sudo systemctl restart apache2
      displayName: "Deploy and Restart Web Server"
