trigger:
  - master  # Correct indentation for the trigger

pool:
  name: ubuntu  # Ensure this matches the actual agent pool name

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
